-- MySQL Script generated by MySQL Workbench
-- Tue Oct 14 22:42:28 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db` ;
USE `db` ;

-- -----------------------------------------------------
-- Table `db`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `usuario` VARCHAR(100) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `telefone` VARCHAR(15) NULL,
  `senha` VARCHAR(255) NOT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `cargo` ENUM('Administrativo', 'Frente de Caixa', 'Repositor', 'Entregador') NOT NULL,
  `is_admin` TINYINT(1) NOT NULL DEFAULT 0,
  `icone` VARCHAR(255) NULL DEFAULT 'default.png',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`permissoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`permissoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `tipo` ENUM('visualizar', 'cadastrar', 'editar', 'deletar') NOT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`permissao_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`permissao_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `permissoes_id` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `permissoes_id`, `usuarios_id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_permissao_usuario_permissoes1_idx` (`permissoes_id` ASC) VISIBLE,
  INDEX `fk_permissao_usuario_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_permissao_usuario_permissoes1`
    FOREIGN KEY (`permissoes_id`)
    REFERENCES `db`.`permissoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_permissao_usuario_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `db`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`grupo_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`grupo_produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP on UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`entrada_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`entrada_produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `quantidade` VARCHAR(100) NOT NULL,
  `tipo` VARCHAR(50) NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP on UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`saida_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`saida_produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `quantidade` VARCHAR(100) NOT NULL,
  `tipo` VARCHAR(50) NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP on UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`icms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`icms` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `tributacao` FLOAT NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`ipi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`ipi` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `tributacao` FLOAT NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`pis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`pis` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `tributacao` FLOAT NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`origem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`origem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`cofins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`cofins` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `tributacao` FLOAT NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`produtos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `codigo` VARCHAR(13) NOT NULL,
  `preco` FLOAT(7,2) NOT NULL,
  `estoque` FLOAT(7,2) NOT NULL,
  `tipo` ENUM('un', 'kg') NOT NULL,
  `grupo_produto_id` INT NOT NULL,
  `entrada_produto_id` INT NOT NULL,
  `saida_produto_id` INT NOT NULL,
  `icms_id` INT NOT NULL,
  `ipi_id` INT NOT NULL,
  `pis_id` INT NOT NULL,
  `cofins_id` INT NOT NULL,
  `origem_id` INT NOT NULL,
  `cfop` INT NOT NULL,
  `ncm` INT(8) NULL,
  `cest` INT NULL,
  `nat_receita` INT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `grupo_produto_id`, `entrada_produto_id`, `saida_produto_id`, `icms_id`, `ipi_id`, `pis_id`, `cofins_id`, `origem_id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_produtos_grupo_produto1_idx` (`grupo_produto_id` ASC) VISIBLE,
  INDEX `fk_produtos_entrada_produto1_idx` (`entrada_produto_id` ASC) VISIBLE,
  INDEX `fk_produtos_saida_produto1_idx` (`saida_produto_id` ASC) VISIBLE,
  INDEX `fk_produtos_icms1_idx` (`icms_id` ASC) VISIBLE,
  INDEX `fk_produtos_ipi1_idx` (`ipi_id` ASC) VISIBLE,
  INDEX `fk_produtos_pis1_idx` (`pis_id` ASC) VISIBLE,
  INDEX `fk_produtos_origem1_idx` (`origem_id` ASC) VISIBLE,
  INDEX `fk_produtos_cofins1_idx` (`cofins_id` ASC) VISIBLE,
  CONSTRAINT `fk_produtos_grupo_produto1`
    FOREIGN KEY (`grupo_produto_id`)
    REFERENCES `db`.`grupo_produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_entrada_produto1`
    FOREIGN KEY (`entrada_produto_id`)
    REFERENCES `db`.`entrada_produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_saida_produto1`
    FOREIGN KEY (`saida_produto_id`)
    REFERENCES `db`.`saida_produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_icms1`
    FOREIGN KEY (`icms_id`)
    REFERENCES `db`.`icms` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_ipi1`
    FOREIGN KEY (`ipi_id`)
    REFERENCES `db`.`ipi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_pis1`
    FOREIGN KEY (`pis_id`)
    REFERENCES `db`.`pis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_origem1`
    FOREIGN KEY (`origem_id`)
    REFERENCES `db`.`origem` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_cofins1`
    FOREIGN KEY (`cofins_id`)
    REFERENCES `db`.`cofins` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`vendas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `desconto` INT(100) NOT NULL DEFAULT 0,
  `total` FLOAT(7,2) NULL,
  `troco` FLOAT(7,2) NOT NULL DEFAULT 0,
  `usuarios_id` INT NOT NULL,
  `situacao` ENUM('cancelada', 'em andamento', 'em espera', 'concluida') NOT NULL DEFAULT 'em andamento',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `usuarios_id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_vendas_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_vendas_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `db`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`venda_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`venda_produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `quantidade` FLOAT(7,2) NOT NULL DEFAULT 1,
  `vendas_id` INT NOT NULL,
  `produtos_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `vendas_id`, `produtos_id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_venda_produto_produtos1_idx` (`produtos_id` ASC) VISIBLE,
  INDEX `fk_venda_produto_vendas1_idx` (`vendas_id` ASC) VISIBLE,
  CONSTRAINT `fk_venda_produto_produtos1`
    FOREIGN KEY (`produtos_id`)
    REFERENCES `db`.`produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_produto_vendas1`
    FOREIGN KEY (`vendas_id`)
    REFERENCES `db`.`vendas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`enderecos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `cep` VARCHAR(10) NOT NULL,
  `uf` VARCHAR(2) NULL,
  `codigo` INT NULL,
  `cidade` VARCHAR(150) NOT NULL,
  `rua` VARCHAR(255) NOT NULL,
  `bairro` VARCHAR(255) NOT NULL,
  `numero` VARCHAR(10) NOT NULL DEFAULT 'S/N',
  `complemento` VARCHAR(255) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NULL,
  `documento` VARCHAR(18) NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `ie_rg` VARCHAR(10) NOT NULL DEFAULT 'ISENTO',
  `contribuinte` TINYINT(1) NOT NULL DEFAULT 0,
  `enderecos_id` INT NOT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `enderecos_id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_clientes_enderecos1_idx` (`enderecos_id` ASC) VISIBLE,
  CONSTRAINT `fk_clientes_enderecos1`
    FOREIGN KEY (`enderecos_id`)
    REFERENCES `db`.`enderecos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`recuperar_senha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`recuperar_senha` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `usuarios_id` INT NOT NULL,
  `codigo` INT(6) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `usuarios_id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_recuperar_senha_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_recuperar_senha_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `db`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`venda_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`venda_cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `clientes_id` INT NOT NULL,
  `vendas_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `clientes_id`, `vendas_id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_venda_fiado_clientes1_idx` (`clientes_id` ASC) VISIBLE,
  INDEX `fk_venda_fiado_vendas1_idx` (`vendas_id` ASC) VISIBLE,
  CONSTRAINT `fk_venda_fiado_clientes1`
    FOREIGN KEY (`clientes_id`)
    REFERENCES `db`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_fiado_vendas1`
    FOREIGN KEY (`vendas_id`)
    REFERENCES `db`.`vendas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`pagamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `forma` VARCHAR(100) NOT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`venda_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`venda_pagamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `vendas_id` INT NOT NULL,
  `pagamento_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `vendas_id`, `pagamento_id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_venda_pagamento_vendas1_idx` (`vendas_id` ASC) VISIBLE,
  INDEX `fk_venda_pagamento_pagamento1_idx` (`pagamento_id` ASC) VISIBLE,
  CONSTRAINT `fk_venda_pagamento_vendas1`
    FOREIGN KEY (`vendas_id`)
    REFERENCES `db`.`vendas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_pagamento_pagamento1`
    FOREIGN KEY (`pagamento_id`)
    REFERENCES `db`.`pagamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`emitente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`emitente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `razao_social` VARCHAR(255) NOT NULL,
  `nome_fantasia` VARCHAR(255) NOT NULL,
  `documento` VARCHAR(20) NOT NULL,
  `ie_rg` VARCHAR(10) NOT NULL,
  `num_serie_nfe` INT NOT NULL,
  `enderecos_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `enderecos_id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_emitente_enderecos1_idx` (`enderecos_id` ASC) VISIBLE,
  CONSTRAINT `fk_emitente_enderecos1`
    FOREIGN KEY (`enderecos_id`)
    REFERENCES `db`.`enderecos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
