-- MySQL Script generated by MySQL Workbench
-- Thu Oct 16 16:46:56 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db` ;
USE `db` ;

-- -----------------------------------------------------
-- Table `db`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `usuario` VARCHAR(100) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `telefone` VARCHAR(15) NULL,
  `senha` VARCHAR(255) NOT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `cargo` ENUM('Administrativo', 'Frente de Caixa', 'Repositor', 'Entregador') NOT NULL,
  `is_admin` TINYINT(1) NOT NULL DEFAULT 0,
  `icone` VARCHAR(255) NULL DEFAULT 'default.png',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`permissoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`permissoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `tipo` ENUM('visualizar', 'cadastrar', 'editar', 'deletar') NOT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`permissao_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`permissao_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `permissoes_id` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `permissoes_id`, `usuarios_id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_permissao_usuario_permissoes1_idx` (`permissoes_id` ASC) VISIBLE,
  INDEX `fk_permissao_usuario_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_permissao_usuario_permissoes1`
    FOREIGN KEY (`permissoes_id`)
    REFERENCES `db`.`permissoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_permissao_usuario_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `db`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`grupo_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`grupo_produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP on UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`entrada_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`entrada_produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `quantidade` VARCHAR(100) NOT NULL,
  `tipo` VARCHAR(50) NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP on UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`saida_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`saida_produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `quantidade` VARCHAR(100) NOT NULL,
  `tipo` VARCHAR(50) NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP on UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`icms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`icms` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `tributacao` FLOAT NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`ipi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`ipi` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `tributacao` FLOAT NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`pis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`pis` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `tributacao` FLOAT NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`origem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`origem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`cofins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`cofins` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `tributacao` FLOAT NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`produtos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `codigo` VARCHAR(13) NOT NULL,
  `preco` FLOAT(7,2) NOT NULL,
  `estoque` FLOAT(7,2) NOT NULL,
  `tipo` ENUM('un', 'kg') NOT NULL,
  `grupo_produto_id` INT NOT NULL,
  `entrada_produto_id` INT NOT NULL,
  `saida_produto_id` INT NOT NULL,
  `icms_id` INT NOT NULL,
  `ipi_id` INT NOT NULL,
  `pis_id` INT NOT NULL,
  `cofins_id` INT NOT NULL,
  `origem_id` INT NOT NULL,
  `cfop` INT NOT NULL,
  `ncm` INT(8) NULL,
  `cest` INT NULL,
  `nat_receita` INT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_produtos_grupo_produto1_idx` (`grupo_produto_id` ASC) VISIBLE,
  INDEX `fk_produtos_entrada_produto1_idx` (`entrada_produto_id` ASC) VISIBLE,
  INDEX `fk_produtos_saida_produto1_idx` (`saida_produto_id` ASC) VISIBLE,
  INDEX `fk_produtos_icms1_idx` (`icms_id` ASC) VISIBLE,
  INDEX `fk_produtos_ipi1_idx` (`ipi_id` ASC) VISIBLE,
  INDEX `fk_produtos_pis1_idx` (`pis_id` ASC) VISIBLE,
  INDEX `fk_produtos_origem1_idx` (`origem_id` ASC) VISIBLE,
  INDEX `fk_produtos_cofins1_idx` (`cofins_id` ASC) VISIBLE,
  CONSTRAINT `fk_produtos_grupo_produto1`
    FOREIGN KEY (`grupo_produto_id`)
    REFERENCES `db`.`grupo_produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_entrada_produto1`
    FOREIGN KEY (`entrada_produto_id`)
    REFERENCES `db`.`entrada_produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_saida_produto1`
    FOREIGN KEY (`saida_produto_id`)
    REFERENCES `db`.`saida_produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_icms1`
    FOREIGN KEY (`icms_id`)
    REFERENCES `db`.`icms` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_ipi1`
    FOREIGN KEY (`ipi_id`)
    REFERENCES `db`.`ipi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_pis1`
    FOREIGN KEY (`pis_id`)
    REFERENCES `db`.`pis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_origem1`
    FOREIGN KEY (`origem_id`)
    REFERENCES `db`.`origem` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_cofins1`
    FOREIGN KEY (`cofins_id`)
    REFERENCES `db`.`cofins` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`vendas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `desconto` INT(100) NOT NULL DEFAULT 0,
  `total` FLOAT(7,2) NULL,
  `troco` FLOAT(7,2) NOT NULL DEFAULT 0,
  `usuarios_id` INT NOT NULL,
  `situacao` ENUM('cancelada', 'em andamento', 'em espera', 'concluida') NOT NULL DEFAULT 'em andamento',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_vendas_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_vendas_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `db`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`venda_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`venda_produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `quantidade` FLOAT(7,2) NOT NULL DEFAULT 1,
  `vendas_id` INT NOT NULL,
  `produtos_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `vendas_id`, `produtos_id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_venda_produto_vendas1_idx` (`vendas_id` ASC) VISIBLE,
  INDEX `fk_venda_produto_produtos1_idx` (`produtos_id` ASC) VISIBLE,
  CONSTRAINT `fk_venda_produto_produtos1`
    FOREIGN KEY (`produtos_id`)
    REFERENCES `db`.`produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_produto_vendas1`
    FOREIGN KEY (`vendas_id`)
    REFERENCES `db`.`vendas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`enderecos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `cep` VARCHAR(10) NOT NULL,
  `uf` VARCHAR(2) NULL,
  `codigo` INT NULL,
  `cidade` VARCHAR(150) NOT NULL,
  `rua` VARCHAR(255) NOT NULL,
  `bairro` VARCHAR(255) NOT NULL,
  `numero` VARCHAR(10) NOT NULL DEFAULT 'S/N',
  `complemento` VARCHAR(255) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NULL,
  `documento` VARCHAR(18) NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `ie_rg` VARCHAR(10) NOT NULL DEFAULT 'ISENTO',
  `contribuinte` TINYINT(1) NOT NULL DEFAULT 0,
  `enderecos_id` INT NOT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_clientes_enderecos1_idx` (`enderecos_id` ASC) VISIBLE,
  CONSTRAINT `fk_clientes_enderecos1`
    FOREIGN KEY (`enderecos_id`)
    REFERENCES `db`.`enderecos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`recuperar_senha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`recuperar_senha` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `usuarios_id` INT NOT NULL,
  `codigo` INT(6) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `usuarios_id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_recuperar_senha_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_recuperar_senha_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `db`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`venda_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`venda_cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `clientes_id` INT NOT NULL,
  `vendas_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `clientes_id`, `vendas_id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_venda_fiado_clientes1_idx` (`clientes_id` ASC) VISIBLE,
  INDEX `fk_venda_fiado_vendas1_idx` (`vendas_id` ASC) VISIBLE,
  CONSTRAINT `fk_venda_fiado_clientes1`
    FOREIGN KEY (`clientes_id`)
    REFERENCES `db`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_fiado_vendas1`
    FOREIGN KEY (`vendas_id`)
    REFERENCES `db`.`vendas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`pagamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `forma` VARCHAR(100) NOT NULL,
  `ativo` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`venda_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`venda_pagamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `vendas_id` INT NOT NULL,
  `pagamento_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `vendas_id`, `pagamento_id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_venda_pagamento_vendas1_idx` (`vendas_id` ASC) VISIBLE,
  INDEX `fk_venda_pagamento_pagamento1_idx` (`pagamento_id` ASC) VISIBLE,
  CONSTRAINT `fk_venda_pagamento_vendas1`
    FOREIGN KEY (`vendas_id`)
    REFERENCES `db`.`vendas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_pagamento_pagamento1`
    FOREIGN KEY (`pagamento_id`)
    REFERENCES `db`.`pagamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`emitente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`emitente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `razao_social` VARCHAR(255) NOT NULL,
  `nome_fantasia` VARCHAR(255) NOT NULL,
  `documento` VARCHAR(20) NOT NULL,
  `ie_rg` VARCHAR(10) NOT NULL,
  `num_serie_nfe` INT NOT NULL,
  `enderecos_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `enderecos_id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_emitente_enderecos1_idx` (`enderecos_id` ASC) VISIBLE,
  CONSTRAINT `fk_emitente_enderecos1`
    FOREIGN KEY (`enderecos_id`)
    REFERENCES `db`.`enderecos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- INSERÇÃO DE EMBALAGENS DE ENTRADA
insert into entrada_produto set uuid="eac03e98-8d23-4f66-8cff-90952d02g47c", quantidade=1, tipo="UN", ativo=1;
insert into entrada_produto set uuid="bad52b44-9c73-4d99-afb3-502cgda1e12c", quantidade=24, tipo="CX", ativo=1;
insert into entrada_produto set uuid="7fb2d9d3-6b7a-4f1a-9c2a-13ba8gdad013", quantidade=12, tipo="CX", ativo=1;
insert into entrada_produto set uuid="bad52b44-9c73-4d99-afb3-502caa1e1fdc", quantidade=8, tipo="CX", ativo=1;
insert into entrada_produto set uuid="bad52b44-9c73-4d99-afb3-502cagffde2c", quantidade=6, tipo="CX", ativo=1;
insert into entrada_produto set uuid="bad52b44-9c73-4d99-afb3-502cagakge2c", quantidade=4, tipo="CX", ativo=1;
insert into entrada_produto set uuid="b1e4f89c-98d1-4325-a6c7-44bc31k4ka2e", quantidade=24, tipo="FD", ativo=1;
insert into entrada_produto set uuid="b1e4f89c-98d1-4325-a6c7-44bc3kkg51a2", quantidade=12, tipo="FD", ativo=1;
insert into entrada_produto set uuid="b1e4f89c-98d1-4325-a6c7-44bc31k31l2e", quantidade=8, tipo="FD", ativo=1;
insert into entrada_produto set uuid="b1e4f89c-98d1-4325-a6c7-44bc3kg51a2e", quantidade=6, tipo="FD", ativo=1;
insert into entrada_produto set uuid="b1e4f89c-98d1-4325-a6c7-44bc3lk51a2e", quantidade=4, tipo="FD", ativo=1;
insert into entrada_produto set uuid="cd176a8f-c54f-4165-a16e-e66b1kldl5c6", quantidade=24, tipo="PC", ativo=1;
insert into entrada_produto set uuid="cd176a8f-c54f-4165-a16e-e66bfc0hb5c6", quantidade=12, tipo="PC", ativo=1;
insert into entrada_produto set uuid="cd176a8f-c54f-4165-a16e-e66b1y0d25c6", quantidade=8, tipo="PC", ativo=1;
insert into entrada_produto set uuid="cd176a8f-c54f-4165-a16e-e66b1c0dbfc6", quantidade=6, tipo="PC", ativo=1;
insert into entrada_produto set uuid="cd176a8f-c54f-4165-a16e-e66b1c0db5c6", quantidade=4, tipo="PC", ativo=1;
insert into entrada_produto set uuid="481917f6-8473-4de0-9c30-4c160434e7cb", quantidade=24, tipo="SC", ativo=1;
insert into entrada_produto set uuid="481917f6-8473-4de0-9c30-4c1604fbe7cb", quantidade=12, tipo="SC", ativo=1;
insert into entrada_produto set uuid="481917f6-8473-4de0-9c30-4c160f3ge7cb", quantidade=8, tipo="SC", ativo=1;
insert into entrada_produto set uuid="481917f6-8473-4de0-9c30-4c16053be7cb", quantidade=4, tipo="SC", ativo=1;
insert into entrada_produto set uuid="0dbf7e2a-61f4-4b4b-af43-cc64cg90brab", quantidade=1, tipo="KG", ativo=1;

-- INSERÇÃO DE EMBALAGENS DE SAÍDA
insert into saida_produto set uuid="eac03e98-8d23-4f66-8cff-90952d02g47c", quantidade=1, tipo="UN", ativo=1;
insert into saida_produto set uuid="bad52b44-9c73-4d99-afb3-502cgda1e12c", quantidade=24, tipo="CX", ativo=1;
insert into saida_produto set uuid="7fb2d9d3-6b7a-4f1a-9c2a-13ba8gdad013", quantidade=12, tipo="CX", ativo=1;
insert into saida_produto set uuid="bad52b44-9c73-4d99-afb3-502caa1e1fdc", quantidade=8, tipo="CX", ativo=1;
insert into saida_produto set uuid="bad52b44-9c73-4d99-afb3-502cagffde2c", quantidade=6, tipo="CX", ativo=1;
insert into saida_produto set uuid="bad52b44-9c73-4d99-afb3-502cagakge2c", quantidade=4, tipo="CX", ativo=1;
insert into saida_produto set uuid="b1e4f89c-98d1-4325-a6c7-44bc31k4ka2e", quantidade=24, tipo="FD", ativo=1;
insert into saida_produto set uuid="b1e4f89c-98d1-4325-a6c7-44bc3kkg51a2", quantidade=12, tipo="FD", ativo=1;
insert into saida_produto set uuid="b1e4f89c-98d1-4325-a6c7-44bc31k31l2e", quantidade=8, tipo="FD", ativo=1;
insert into saida_produto set uuid="b1e4f89c-98d1-4325-a6c7-44bc3kg51a2e", quantidade=6, tipo="FD", ativo=1;
insert into saida_produto set uuid="b1e4f89c-98d1-4325-a6c7-44bc3lk51a2e", quantidade=4, tipo="FD", ativo=1;
insert into saida_produto set uuid="cd176a8f-c54f-4165-a16e-e66b1kldl5c6", quantidade=24, tipo="PC", ativo=1;
insert into saida_produto set uuid="cd176a8f-c54f-4165-a16e-e66bfc0hb5c6", quantidade=12, tipo="PC", ativo=1;
insert into saida_produto set uuid="cd176a8f-c54f-4165-a16e-e66b1y0d25c6", quantidade=8, tipo="PC", ativo=1;
insert into saida_produto set uuid="cd176a8f-c54f-4165-a16e-e66b1c0dbfc6", quantidade=6, tipo="PC", ativo=1;
insert into saida_produto set uuid="cd176a8f-c54f-4165-a16e-e66b1c0db5c6", quantidade=4, tipo="PC", ativo=1;
insert into saida_produto set uuid="481917f6-8473-4de0-9c30-4c160434e7cb", quantidade=24, tipo="SC", ativo=1;
insert into saida_produto set uuid="481917f6-8473-4de0-9c30-4c1604fbe7cb", quantidade=12, tipo="SC", ativo=1;
insert into saida_produto set uuid="481917f6-8473-4de0-9c30-4c160f3ge7cb", quantidade=8, tipo="SC", ativo=1;
insert into saida_produto set uuid="481917f6-8473-4de0-9c30-4c16053be7cb", quantidade=4, tipo="SC", ativo=1;
insert into saida_produto set uuid="0dbf7e2a-61f4-4b4b-af43-cc64cg90brab", quantidade=1, tipo="KG", ativo=1;

-- INSERÇÃO DE ORIGEM

insert into origem set codigo=0, nome="Nacional", uuid="7e4c3f1d-0c9f-4af0-b3af-9df6e8e2b4e1", ativo=1;
insert into origem set codigo=1, nome="Estrangeira – Importação Direta", uuid="c2b3bca4-1df2-4d6e-a93d-8ad7ae601d45", ativo=1;
insert into origem set codigo=2, nome="Estrangeira – Adquirida no Mercado Interno", uuid="5f7a98aa-c2fe-4e32-a69c-139ef9d3145b", ativo=1;
insert into origem set codigo=3, nome="Nacional com Conteúdo de Importação > 40%", uuid="d9c35b78-e3fb-4e79-8b98-1576936af7d4", ativo=1;
insert into origem set codigo=4, nome="Nacional Produzida conforme PPB", uuid="0f3f0c4c-67ad-4e6e-b6be-c6c3b99df2a1", ativo=1;
insert into origem set codigo=5, nome="Nacional com Conteúdo de Importação ≤ 40%", uuid="b33e6f90-2a90-49cd-8e19-7543b9d9e0ed", ativo=1;
insert into origem set codigo=6, nome="Estrangeira – Importação Direta sem Similar Nacional", uuid="9a8b4bd7-2fd0-4c62-b06d-2410d62b87ea", ativo=1;
insert into origem set codigo=7, nome="Estrangeira – Mercado Interno sem Similar Nacional", uuid="fb1d2337-008f-4979-ada6-4fa56735d5d2", ativo=1;
insert into origem set codigo=8, nome="Nacional – Conteúdo de Importação Indeterminado", uuid="e47241e0-774d-459e-b1b7-a2e8b93fe629", ativo=1;

-- INSERÇÃO DE Natureza da receita
-- insert into origem set uuid = "7a1c8288-54c3-4e27-9db0-34c1f548c210", codigo = 0, nome = "Nacional, exceto as indicadas nos códigos 3, 4, 5 e 8", ativo = 1;
-- insert into origem set uuid = "b92df96e-6de5-48fc-9e4d-2e0189ab5e2b", codigo = 1, nome = "Estrangeira – Importação direta, exceto a indicada no código 6", ativo = 1;
-- insert into origem set uuid = "e4c2a2f0-f92d-4a86-9e0c-0bbd1b7a1329", codigo = 2, nome = "Estrangeira – Adquirida no mercado interno, exceto a indicada no código 7", ativo = 1;
-- insert into origem set uuid = "0f9c88f7-0d72-49f6-af68-2d3f0e3d89a1", codigo = 3, nome = "Nacional, mercadoria ou bem com Conteúdo de Importação superior a 40% e inferior ou igual a 70%", ativo = 1;
-- insert into origem set uuid = "1dc8b0f1-1e1b-4df7-bb68-998a6fce12fb", codigo = 4, nome = "Nacional, cuja produção tenha sido realizada em conformidade com processos produtivos básicos (PPB)", ativo = 1;
-- insert into origem set uuid = "c2d3e2ac-4742-4c83-ac13-6cc89b447fc2", codigo = 5, nome = "Nacional, mercadoria ou bem com Conteúdo de Importação inferior ou igual a 40%", ativo = 1;
-- insert into origem set uuid = "3c5949e0-87b7-4c0a-bb13-b7a0d72af326", codigo = 6, nome = "Estrangeira – Importação direta, sem similar nacional, constante na lista CAMEX", ativo = 1;
-- insert into origem set uuid = "9b7e1d3f-f4d3-44df-ac07-c96857e946c8", codigo = 7, nome = "Estrangeira – Adquirida no mercado interno, sem similar nacional, constante na lista CAMEX", ativo = 1;
-- insert into origem set uuid = "f81cabc9-d7e4-497a-b121-b1d464b5a021", codigo = 8, nome = "Nacional, mercadoria ou bem com Conteúdo de Importação superior a 70%", ativo = 1;
